package org.async4j.util;

import org.async4j.Callback;

/**
 * Defines the method {@link #handleElement(Callback, Object)} which handle elements generated by {@link Producer} 
 * @author Amah AHITE
 *
 * @param <E> type of elements to be handled
 */
public interface ElementHandler<E> {
	public void handleElement(Callback<Void> k, E e);
}
